<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_n3sGgOPSEeyt9O6Qe0AcVQ" name="Faturação" author="luis" bonitaVersion="7.14.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_n3sGgePSEeyt9O6Qe0AcVQ" name="Validar Fatura">
      <elements xmi:type="process:Lane" xmi:id="_n3sGguPSEeyt9O6Qe0AcVQ" name="Employee lane" actor="_n3sGm-PSEeyt9O6Qe0AcVQ">
        <elements xmi:type="process:StartEvent" xmi:id="_n3sGg-PSEeyt9O6Qe0AcVQ" name="_Inicio" outgoing="_n3sGmOPSEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_n3sGhOPSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_n3sGhePSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_n3sGhuPSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_7nxl0OPSEeyt9O6Qe0AcVQ" name="Notificar Utilizador" outgoing="_8m_nIOPSEeyt9O6Qe0AcVQ" incoming="_n3sGmOPSEeyt9O6Qe0AcVQ _DEZIYOPTEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_n3sGiOPSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_n3sGiePSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_n3sGiuPSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_C_ZNcOtDEeyBBbS0Jq0WVg" name="Validar fatura" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_C_ZNcetDEeyBBbS0Jq0WVg" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNcutDEeyBBbS0Jq0WVg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNc-tDEeyBBbS0Jq0WVg" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNdOtDEeyBBbS0Jq0WVg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNdetDEeyBBbS0Jq0WVg" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNdutDEeyBBbS0Jq0WVg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNd-tDEeyBBbS0Jq0WVg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNeOtDEeyBBbS0Jq0WVg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNeetDEeyBBbS0Jq0WVg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNeutDEeyBBbS0Jq0WVg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNe-tDEeyBBbS0Jq0WVg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNfOtDEeyBBbS0Jq0WVg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNfetDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNfutDEeyBBbS0Jq0WVg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNf-tDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNgOtDEeyBBbS0Jq0WVg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNgetDEeyBBbS0Jq0WVg" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNgutDEeyBBbS0Jq0WVg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNg-tDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNhOtDEeyBBbS0Jq0WVg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNhetDEeyBBbS0Jq0WVg" name="client@acme.com" content="client@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNhutDEeyBBbS0Jq0WVg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNh-tDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNiOtDEeyBBbS0Jq0WVg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNietDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNiutDEeyBBbS0Jq0WVg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNi-tDEeyBBbS0Jq0WVg" name="Fatura pendente" content="Fatura pendente" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNjOtDEeyBBbS0Jq0WVg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNjetDEeyBBbS0Jq0WVg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNjutDEeyBBbS0Jq0WVg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNj-tDEeyBBbS0Jq0WVg" name="&lt;pattern-expression>" content="Bom dia, tem uma fatura pendente de validação." type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNkOtDEeyBBbS0Jq0WVg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_C_ZNketDEeyBBbS0Jq0WVg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNkutDEeyBBbS0Jq0WVg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNk-tDEeyBBbS0Jq0WVg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNlOtDEeyBBbS0Jq0WVg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_C_ZNletDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_C_ZNlutDEeyBBbS0Jq0WVg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_C_ZNl-tDEeyBBbS0Jq0WVg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_n3sGi-PSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_n3sGjOPSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_n3sGjePSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_n3sGjuPSEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_n3sGj-PSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_-1yZ8OPSEeyt9O6Qe0AcVQ" name="Validar Fatura" outgoing="_KB5tEOPTEeyt9O6Qe0AcVQ" incoming="_8m_nIOPSEeyt9O6Qe0AcVQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8m6HkuPSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8m6HkePSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8m6Hk-PSEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8m6HlOPSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8m6HlePSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8m6HluPSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8m6HmOPSEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8m6Hl-PSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_AGvEcOPTEeyt9O6Qe0AcVQ" name="1 dia" outgoing="_DEZIYOPTEeyt9O6Qe0AcVQ">
            <condition xmi:type="expression:Expression" xmi:id="_BXeTkOPTEeyt9O6Qe0AcVQ" name="1 Days 00:00:00" content="86400000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-1yZ-uPSEeyt9O6Qe0AcVQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_-1yZ--PSEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-1yZ-ePSEeyt9O6Qe0AcVQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-1yZ_OPSEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_KhSXwOPTEeyt9O6Qe0AcVQ" name="Gateway1" outgoing="_L8IlIOPTEeyt9O6Qe0AcVQ _MyBEQOPTEeyt9O6Qe0AcVQ" incoming="_KB5tEOPTEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KB0NgePTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KB0NgOPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KB0NguPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_L8E6wOPTEeyt9O6Qe0AcVQ" name="Fatura Válida" incoming="_L8IlIOPTEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L8E6wuPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L8E6wePTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L8E6w-PTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Mx8LwOPTEeyt9O6Qe0AcVQ" name="Fatura Inválida" incoming="_MyBEQOPTEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Mx8y0ePTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Mx8y0OPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Mx8y0uPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_n3sGlOPSEeyt9O6Qe0AcVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_n3sGlePSEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_n3sGluPSEeyt9O6Qe0AcVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_n3sGl-PSEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_n3sGmOPSEeyt9O6Qe0AcVQ" target="_7nxl0OPSEeyt9O6Qe0AcVQ" source="_n3sGg-PSEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_n3sGmePSEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_n3sGmuPSEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8m_nIOPSEeyt9O6Qe0AcVQ" target="_-1yZ8OPSEeyt9O6Qe0AcVQ" source="_7nxl0OPSEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8m_nIePSEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_8m_nIuPSEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DEZIYOPTEeyt9O6Qe0AcVQ" target="_7nxl0OPSEeyt9O6Qe0AcVQ" source="_AGvEcOPTEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DEZIYePTEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_DEZIYuPTEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KB5tEOPTEeyt9O6Qe0AcVQ" target="_KhSXwOPTEeyt9O6Qe0AcVQ" source="_-1yZ8OPSEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KB5tEePTEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_KB5tEuPTEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_L8IlIOPTEeyt9O6Qe0AcVQ" name="Sim" target="_L8E6wOPTEeyt9O6Qe0AcVQ" source="_KhSXwOPTEeyt9O6Qe0AcVQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_L8IlIePTEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_L8IlIuPTEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MyBEQOPTEeyt9O6Qe0AcVQ" name="Não" target="_Mx8LwOPTEeyt9O6Qe0AcVQ" source="_KhSXwOPTEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MyBEQePTEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_MyBEQuPTEeyt9O6Qe0AcVQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_n3sGm-PSEeyt9O6Qe0AcVQ" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_n3sGnOPSEeyt9O6Qe0AcVQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_n3sGnePSEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_n3sGnuPSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_n3sGn-PSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_n3sGoOPSEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_n3sGoePSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_n3sGouPSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_n3sGo-PSEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_n3sGpOPSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_n3sGpePSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_n3sGpuPSEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_n3sGp-PSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_n3sGqOPSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_n3sGqePSEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_n3sGquPSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_n3sGq-PSEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_qziXIOPTEeyt9O6Qe0AcVQ" name="Pedido Validação fatura pelos responsáveis">
      <elements xmi:type="process:Lane" xmi:id="_uVaicOPTEeyt9O6Qe0AcVQ" name="Comercial">
        <elements xmi:type="process:StartMessageEvent" xmi:id="_zclQkOPTEeyt9O6Qe0AcVQ" name="Pedido Validação" outgoing="_53k-EOPTEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zcnFwePTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zcnFwOPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zcnFwuPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_6aHqcOPTEeyt9O6Qe0AcVQ" name="Validar  Fatura" outgoing="_-2S60OPTEeyt9O6Qe0AcVQ" incoming="_53k-EOPTEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_53hTsuPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_53hTsePTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_53hTs-PTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_53hTtOPTEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_53hTtePTEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_53hTtuPTEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_53hTuOPTEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_53hTt-PTEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_6aIRg-PTEeyt9O6Qe0AcVQ" name="Validar Fatura" content="Validar Fatura" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_6aIRhOPTEeyt9O6Qe0AcVQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_CS49gOPUEeyt9O6Qe0AcVQ" name="Fatura  Inválida" incoming="_CS8A0OPUEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CS49guPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CS49gePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CS49g-PUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_TwFNIOPUEeyt9O6Qe0AcVQ" name="Fatura Válida" outgoing="_CS8A0OPUEeyt9O6Qe0AcVQ _KKcIkOPUEeyt9O6Qe0AcVQ" incoming="_-2S60OPTEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-2P3gePTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-2P3gOPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-2P3guPTEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_uzdwYOPTEeyt9O6Qe0AcVQ" name="Responsável Técnico">
        <elements xmi:type="process:CallActivity" xmi:id="_KtLpQOPUEeyt9O6Qe0AcVQ" name="Validar Fatura" outgoing="_QyFK8OPUEeyt9O6Qe0AcVQ" incoming="_KKcIkOPUEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KKZFQuPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KKZFQePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KKZFQ-PUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KKZFROPUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KKZFRePUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KKZFRuPUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KKZFSOPUEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KKZFR-PUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_KtMQU-PUEeyt9O6Qe0AcVQ" name="Validar Fatura" content="Validar Fatura" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_KtMQVOPUEeyt9O6Qe0AcVQ" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_TJdSAOPUEeyt9O6Qe0AcVQ" name="Fatura válida?" outgoing="_dAC8oOPUEeyt9O6Qe0AcVQ _gCxt0OPUEeyt9O6Qe0AcVQ" incoming="_QyFK8OPUEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QyCHoePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QyCHoOPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QyCHouPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_c_-rMOPUEeyt9O6Qe0AcVQ" name="Fatura Validada" incoming="_dAC8oOPUEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_c_-rMuPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_c_-rMePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_c_-rM-PUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_gCuDcOPUEeyt9O6Qe0AcVQ" name="Fatura Inválida" incoming="_gCxt0OPUEeyt9O6Qe0AcVQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_gCuDcuPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_gCuDcePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_gCuDc-PUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_qzi-NePTEeyt9O6Qe0AcVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_qzi-NuPTEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_qzi-N-PTEeyt9O6Qe0AcVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_qzi-OOPTEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_53k-EOPTEeyt9O6Qe0AcVQ" target="_6aHqcOPTEeyt9O6Qe0AcVQ" source="_zclQkOPTEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_53k-EePTEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_53k-EuPTEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-2S60OPTEeyt9O6Qe0AcVQ" target="_TwFNIOPUEeyt9O6Qe0AcVQ" source="_6aHqcOPTEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-2S60ePTEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_-2S60uPTEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CS8A0OPUEeyt9O6Qe0AcVQ" name="Não" target="_CS49gOPUEeyt9O6Qe0AcVQ" source="_TwFNIOPUEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CS8A0ePUEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_CS8A0uPUEeyt9O6Qe0AcVQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KKcIkOPUEeyt9O6Qe0AcVQ" name="Sim" target="_KtLpQOPUEeyt9O6Qe0AcVQ" source="_TwFNIOPUEeyt9O6Qe0AcVQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KKcvoOPUEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_KKcvoePUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QyFK8OPUEeyt9O6Qe0AcVQ" target="_TJdSAOPUEeyt9O6Qe0AcVQ" source="_KtLpQOPUEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QyFK8ePUEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_QyFK8uPUEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dAC8oOPUEeyt9O6Qe0AcVQ" name="Sim" target="_c_-rMOPUEeyt9O6Qe0AcVQ" source="_TJdSAOPUEeyt9O6Qe0AcVQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dAC8oePUEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_dAC8ouPUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gCxt0OPUEeyt9O6Qe0AcVQ" name="Não" target="_gCuDcOPUEeyt9O6Qe0AcVQ" source="_TJdSAOPUEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gCxt0ePUEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_gCxt0uPUEeyt9O6Qe0AcVQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_qzi-OePTEeyt9O6Qe0AcVQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qziXIePTEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qziXIuPTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qziXI-PTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qziXJOPTEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qziXJePTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qziXJuPTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qziXJ-PTEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qziXKOPTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qziXKePTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qziXKuPTEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qzi-MOPTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qzi-MePTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qzi-MuPTEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qzi-M-PTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qzi-NOPTEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_sZEVEOPUEeyt9O6Qe0AcVQ" name="Enviar fatura ao cliente">
      <elements xmi:type="process:StartMessageEvent" xmi:id="_wB9uYOPUEeyt9O6Qe0AcVQ" name="Fatura Recebida" outgoing="_05wjwOPUEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_wB-VcePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_wB-VcOPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_wB-VcuPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_05tgcOPUEeyt9O6Qe0AcVQ" name="Enviar fatura ao cliente" outgoing="_2Nh4wOPUEeyt9O6Qe0AcVQ" incoming="_05wjwOPUEeyt9O6Qe0AcVQ _UyLt4OPVEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_05tgcuPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_05tgcePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_05tgc-PUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_05tgdOPUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_05tgdePUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_05tgduPUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_05tgeOPUEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_05tgd-PUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_2Ne1cOPUEeyt9O6Qe0AcVQ" name="Notificar o cliente" outgoing="_6uC2kOPUEeyt9O6Qe0AcVQ" incoming="_2Nh4wOPUEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_2Ne1cuPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_2Ne1cePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_2Ne1c-PUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <connectors xmi:type="process:Connector" xmi:id="_MnGHgOtDEeyBBbS0Jq0WVg" name="Informar cliente" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_MnGHgetDEeyBBbS0Jq0WVg" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHgutDEeyBBbS0Jq0WVg" key="smtpHost">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHg-tDEeyBBbS0Jq0WVg" name="localhost" content="localhost" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHhOtDEeyBBbS0Jq0WVg" key="smtpPort">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHhetDEeyBBbS0Jq0WVg" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHhutDEeyBBbS0Jq0WVg" key="sslSupport">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHh-tDEeyBBbS0Jq0WVg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHiOtDEeyBBbS0Jq0WVg" key="starttlsSupport">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHietDEeyBBbS0Jq0WVg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHiutDEeyBBbS0Jq0WVg" key="trustCertificate">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHi-tDEeyBBbS0Jq0WVg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHjOtDEeyBBbS0Jq0WVg" key="userName">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHjetDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHjutDEeyBBbS0Jq0WVg" key="password">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHj-tDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHkOtDEeyBBbS0Jq0WVg" key="from">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHketDEeyBBbS0Jq0WVg" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHkutDEeyBBbS0Jq0WVg" key="returnPath">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHk-tDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHlOtDEeyBBbS0Jq0WVg" key="to">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHletDEeyBBbS0Jq0WVg" name="client@acme.com" content="client@acme.com" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHlutDEeyBBbS0Jq0WVg" key="bcc">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHl-tDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHmOtDEeyBBbS0Jq0WVg" key="cc">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHmetDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHmutDEeyBBbS0Jq0WVg" key="subject">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHm-tDEeyBBbS0Jq0WVg" name="Fatura enviada" content="Fatura enviada" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHnOtDEeyBBbS0Jq0WVg" key="html">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHnetDEeyBBbS0Jq0WVg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHnutDEeyBBbS0Jq0WVg" key="message">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHn-tDEeyBBbS0Jq0WVg" name="&lt;pattern-expression>" content="Bom dia, a sua fatura foi enviada." type="TYPE_PATTERN" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHoOtDEeyBBbS0Jq0WVg" key="headers">
              <expression xmi:type="expression:TableExpression" xmi:id="_MnGHoetDEeyBBbS0Jq0WVg"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHoutDEeyBBbS0Jq0WVg" key="charset">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHo-tDEeyBBbS0Jq0WVg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHpOtDEeyBBbS0Jq0WVg" key="replyTo">
              <expression xmi:type="expression:Expression" xmi:id="_MnGHpetDEeyBBbS0Jq0WVg" content="" returnTypeFixed="true"/>
            </parameters>
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_MnGHputDEeyBBbS0Jq0WVg" key="attachments">
              <expression xmi:type="expression:ListExpression" xmi:id="_MnGHp-tDEeyBBbS0Jq0WVg"/>
            </parameters>
          </configuration>
        </connectors>
        <loopCondition xmi:type="expression:Expression" xmi:id="_2Ne1dOPUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_2Ne1dePUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2Ne1duPUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_2Ne1eOPUEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_2Ne1d-PUEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:InclusiveGateway" xmi:id="_7GWB0OPUEeyt9O6Qe0AcVQ" name="Gateway2" outgoing="_EF7L8OPVEeyt9O6Qe0AcVQ _UGxZYOPVEeyt9O6Qe0AcVQ" incoming="_6uC2kOPUEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_6t_zQuPUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_6t_zQePUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_6t_zQ-PUEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:IntermediateCatchMessageEvent" xmi:id="_JwydAOPVEeyt9O6Qe0AcVQ" name="Pagamento do Cliente Recebido" outgoing="_LjFhEOPVEeyt9O6Qe0AcVQ" incoming="_EF7L8OPVEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Dh4DsePVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Dh4DsOPVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Dh4DsuPVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_LjAokOPVEeyt9O6Qe0AcVQ" name="Faturação Completa" incoming="_LjFhEOPVEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_LjBPoePVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_LjBPoOPVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_LjBPouPVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_TEp1EOPVEeyt9O6Qe0AcVQ" name="3 Dias" outgoing="_UyLt4OPVEeyt9O6Qe0AcVQ" incoming="_UGxZYOPVEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_TEp1EuPVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_TEp1EePVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_TEp1E-PVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <condition xmi:type="expression:Expression" xmi:id="_XRdMsOPVEeyt9O6Qe0AcVQ" name="3 Days 00:00:00" content="259200000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_sZE8L-PUEeyt9O6Qe0AcVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_sZE8MOPUEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_sZE8MePUEeyt9O6Qe0AcVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_sZE8MuPUEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_05wjwOPUEeyt9O6Qe0AcVQ" target="_05tgcOPUEeyt9O6Qe0AcVQ" source="_wB9uYOPUEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_05wjwePUEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_05wjwuPUEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2Nh4wOPUEeyt9O6Qe0AcVQ" target="_2Ne1cOPUEeyt9O6Qe0AcVQ" source="_05tgcOPUEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2Nh4wePUEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_2Nh4wuPUEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6uC2kOPUEeyt9O6Qe0AcVQ" target="_7GWB0OPUEeyt9O6Qe0AcVQ" source="_2Ne1cOPUEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6uC2kePUEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6uC2kuPUEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EF7L8OPVEeyt9O6Qe0AcVQ" target="_JwydAOPVEeyt9O6Qe0AcVQ" source="_7GWB0OPUEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EF7L8ePVEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_EF7L8uPVEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LjFhEOPVEeyt9O6Qe0AcVQ" target="_LjAokOPVEeyt9O6Qe0AcVQ" source="_JwydAOPVEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LjFhEePVEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_LjFhEuPVEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UGxZYOPVEeyt9O6Qe0AcVQ" target="_TEp1EOPVEeyt9O6Qe0AcVQ" source="_7GWB0OPUEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UGyAcOPVEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_UGyAcePVEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UyLt4OPVEeyt9O6Qe0AcVQ" target="_05tgcOPUEeyt9O6Qe0AcVQ" source="_TEp1EOPVEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UyLt4ePVEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_UyMU8OPVEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_sZE8M-PUEeyt9O6Qe0AcVQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sZE8IOPUEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_sZE8IePUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sZE8IuPUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sZE8I-PUEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_sZE8JOPUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sZE8JePUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sZE8JuPUEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_sZE8J-PUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sZE8KOPUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sZE8KePUEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_sZE8KuPUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sZE8K-PUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_sZE8LOPUEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_sZE8LePUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_sZE8LuPUEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_qX7uUOPVEeyt9O6Qe0AcVQ" name="Faturação Mensal">
      <elements xmi:type="process:StartTimerEvent" xmi:id="_yXx5wOPVEeyt9O6Qe0AcVQ" name="Início de Cada Mês" outgoing="_QHsfQOPWEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_yXx5wuPVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_yXx5wePVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_yXx5w-PVEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <condition xmi:type="expression:Expression" xmi:id="_yz2xwOPVEeyt9O6Qe0AcVQ" name="0 0 0 1 1/1 ? *" content="0 0 0 1 1/1 ? *" interpreter="GROOVY"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_QHpb8OPWEeyt9O6Qe0AcVQ" name="Criação da Fatura ERP" outgoing="_TwmfoOPWEeyt9O6Qe0AcVQ" incoming="_QHsfQOPWEeyt9O6Qe0AcVQ _1T7FUOPWEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_QHqDAOPWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_QHpb8ePWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_QHqDAePWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_QHqDAuPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_QHqDA-PWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QHqDBOPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_QHqDBuPWEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_QHqDBePWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:CallActivity" xmi:id="_buLaMOPWEeyt9O6Qe0AcVQ" name="Pedido Validação fatura pelos responsáveis" outgoing="_jDpy8OPWEeyt9O6Qe0AcVQ" incoming="_TwmfoOPWEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_TwjcUePWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_TwjcUOPWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_TwjcUuPWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_TwjcU-PWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_TwjcVOPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TwjcVePWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_TwjcV-PWEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_TwjcVuPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <calledActivityName xmi:type="expression:Expression" xmi:id="_buLaNOPWEeyt9O6Qe0AcVQ" name="Pedido Validação fatura pelos responsáveis" content="Pedido Validação fatura pelos responsáveis" returnTypeFixed="true"/>
        <calledActivityVersion xmi:type="expression:Expression" xmi:id="_buLaNePWEeyt9O6Qe0AcVQ" name="1.0" content="1.0" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_jjiz8OPWEeyt9O6Qe0AcVQ" name="Fatura válida?" outgoing="_kX63MOPWEeyt9O6Qe0AcVQ _zTyZkOPWEeyt9O6Qe0AcVQ" incoming="_jDpy8OPWEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_jDnWsuPWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_jDnWsePWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_jDnWs-PWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:CallActivity" xmi:id="_oRiNEOPWEeyt9O6Qe0AcVQ" name="Enviar fatura ao cliente" outgoing="_uXHEMOPWEeyt9O6Qe0AcVQ" incoming="_kX63MOPWEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_kX3z4uPWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_kX3z4ePWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_kX3z4-PWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_kX3z5OPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_kX3z5ePWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kX3z5uPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_kX3z6OPWEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_kX3z5-PWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <calledActivityName xmi:type="expression:Expression" xmi:id="_oRiNFOPWEeyt9O6Qe0AcVQ" name="Enviar fatura ao cliente" content="Enviar fatura ao cliente" returnTypeFixed="true"/>
        <calledActivityVersion xmi:type="expression:Expression" xmi:id="_oRiNFePWEeyt9O6Qe0AcVQ" name="1.0" content="1.0" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_uXEA4OPWEeyt9O6Qe0AcVQ" name="Fatura Enviada" incoming="_uXHEMOPWEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_uXEn8ePWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_uXEn8OPWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_uXEn8uPWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_zTvWQOPWEeyt9O6Qe0AcVQ" name="Atualizar horas da faturação" outgoing="_1T7FUOPWEeyt9O6Qe0AcVQ" incoming="_zTyZkOPWEeyt9O6Qe0AcVQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_zTvWQuPWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_zTvWQePWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_zTvWQ-PWEeyt9O6Qe0AcVQ" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_zTvWROPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_zTvWRePWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zTvWRuPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_zTv9UOPWEeyt9O6Qe0AcVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_zTvWR-PWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_qX7uYOPVEeyt9O6Qe0AcVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_qX7uYePVEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_qX7uYuPVEeyt9O6Qe0AcVQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_qX7uY-PVEeyt9O6Qe0AcVQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QHsfQOPWEeyt9O6Qe0AcVQ" target="_QHpb8OPWEeyt9O6Qe0AcVQ" source="_yXx5wOPVEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QHsfQePWEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_QHsfQuPWEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TwmfoOPWEeyt9O6Qe0AcVQ" target="_buLaMOPWEeyt9O6Qe0AcVQ" source="_QHpb8OPWEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TwmfoePWEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_TwmfouPWEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jDpy8OPWEeyt9O6Qe0AcVQ" target="_jjiz8OPWEeyt9O6Qe0AcVQ" source="_buLaMOPWEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jDpy8ePWEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jDpy8uPWEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kX63MOPWEeyt9O6Qe0AcVQ" name="Sim" target="_oRiNEOPWEeyt9O6Qe0AcVQ" source="_jjiz8OPWEeyt9O6Qe0AcVQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kX63MePWEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kX63MuPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uXHEMOPWEeyt9O6Qe0AcVQ" target="_uXEA4OPWEeyt9O6Qe0AcVQ" source="_oRiNEOPWEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uXHrQOPWEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_uXHrQePWEeyt9O6Qe0AcVQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zTyZkOPWEeyt9O6Qe0AcVQ" name="Não" target="_zTvWQOPWEeyt9O6Qe0AcVQ" source="_jjiz8OPWEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zTzAoOPWEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_zTzAoePWEeyt9O6Qe0AcVQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1T7FUOPWEeyt9O6Qe0AcVQ" target="_QHpb8OPWEeyt9O6Qe0AcVQ" source="_zTvWQOPWEeyt9O6Qe0AcVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1T7FUePWEeyt9O6Qe0AcVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1T7FUuPWEeyt9O6Qe0AcVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_qX7uZOPVEeyt9O6Qe0AcVQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qX7uUePVEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qX7uUuPVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qX7uU-PVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qX7uVOPVEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qX7uVePVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qX7uVuPVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qX7uV-PVEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qX7uWOPVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qX7uWePVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qX7uWuPVEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qX7uW-PVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qX7uXOPVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_qX7uXePVEeyt9O6Qe0AcVQ">
        <name xmi:type="expression:Expression" xmi:id="_qX7uXuPVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_qX7uX-PVEeyt9O6Qe0AcVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_n3sGrOPSEeyt9O6Qe0AcVQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_n3sGrePSEeyt9O6Qe0AcVQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_n3sGruPSEeyt9O6Qe0AcVQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_n3sGr-PSEeyt9O6Qe0AcVQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_n3sGsOPSEeyt9O6Qe0AcVQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_n3sGsePSEeyt9O6Qe0AcVQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_n3sGsuPSEeyt9O6Qe0AcVQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_n3sGs-PSEeyt9O6Qe0AcVQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_n3sGtOPSEeyt9O6Qe0AcVQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_n3sGtePSEeyt9O6Qe0AcVQ" type="Process" element="_n3sGgOPSEeyt9O6Qe0AcVQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_n3sGtuPSEeyt9O6Qe0AcVQ" type="2007" element="_n3sGgePSEeyt9O6Qe0AcVQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_n3sGt-PSEeyt9O6Qe0AcVQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_n3sGuOPSEeyt9O6Qe0AcVQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_n3sGuePSEeyt9O6Qe0AcVQ" type="3007" element="_n3sGguPSEeyt9O6Qe0AcVQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_n3sGuuPSEeyt9O6Qe0AcVQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_n3sGu-PSEeyt9O6Qe0AcVQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_n3sGv-PSEeyt9O6Qe0AcVQ" type="3002" element="_n3sGg-PSEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_n3sGwOPSEeyt9O6Qe0AcVQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_n3sGwePSEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_n3sGwuPSEeyt9O6Qe0AcVQ" x="60" y="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7nyz8OPSEeyt9O6Qe0AcVQ" type="3027" element="_7nxl0OPSEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7nyz8uPSEeyt9O6Qe0AcVQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7nyz8ePSEeyt9O6Qe0AcVQ" x="161" y="99" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-1zBAOPSEeyt9O6Qe0AcVQ" type="3005" element="_-1yZ8OPSEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-1zBAuPSEeyt9O6Qe0AcVQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_AGvrgOPTEeyt9O6Qe0AcVQ" type="3064" element="_AGvEcOPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
                <children xmi:type="notation:DecorationNode" xmi:id="_AGvrguPTEeyt9O6Qe0AcVQ" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_AGvrg-PTEeyt9O6Qe0AcVQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AGvrgePTEeyt9O6Qe0AcVQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-1zBAePSEeyt9O6Qe0AcVQ" x="335" y="105" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KhS-0-PTEeyt9O6Qe0AcVQ" type="3008" element="_KhSXwOPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_KhS-1ePTEeyt9O6Qe0AcVQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_KhS-1uPTEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KhS-1OPTEeyt9O6Qe0AcVQ" x="495" y="108" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L8E6xOPTEeyt9O6Qe0AcVQ" type="3003" element="_L8E6wOPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_L8Fh0OPTEeyt9O6Qe0AcVQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_L8Fh0ePTEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L8E6xePTEeyt9O6Qe0AcVQ" x="649" y="171"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Mx8y0-PTEeyt9O6Qe0AcVQ" type="3003" element="_Mx8LwOPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Mx8y1ePTEeyt9O6Qe0AcVQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Mx9Z4OPTEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Mx8y1OPTEeyt9O6Qe0AcVQ" x="647" y="105"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_n3sGw-PSEeyt9O6Qe0AcVQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_n3sGxOPSEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_n3sGxePSEeyt9O6Qe0AcVQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_n3sGxuPSEeyt9O6Qe0AcVQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_n3sGx-PSEeyt9O6Qe0AcVQ"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_n3sGyOPSEeyt9O6Qe0AcVQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_n3sGyePSEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_n3sGyuPSEeyt9O6Qe0AcVQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_n3sGy-PSEeyt9O6Qe0AcVQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_n3sGzOPSEeyt9O6Qe0AcVQ" width="840" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_qzi-OuPTEeyt9O6Qe0AcVQ" type="2007" element="_qziXIOPTEeyt9O6Qe0AcVQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_qzi-P-PTEeyt9O6Qe0AcVQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_qzi-QOPTEeyt9O6Qe0AcVQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_uVbJgOPTEeyt9O6Qe0AcVQ" type="3007" element="_uVaicOPTEeyt9O6Qe0AcVQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_uVbJhePTEeyt9O6Qe0AcVQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_uVbJhuPTEeyt9O6Qe0AcVQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_zcns0OPTEeyt9O6Qe0AcVQ" type="3012" element="_zclQkOPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_zcns0uPTEeyt9O6Qe0AcVQ" type="5029">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_zcns0-PTEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zcns0ePTEeyt9O6Qe0AcVQ" x="49" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6aIRiuPTEeyt9O6Qe0AcVQ" type="3063" element="_6aHqcOPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6aIRjOPTEeyt9O6Qe0AcVQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6aIRi-PTEeyt9O6Qe0AcVQ" x="138" y="98" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CS5kkOPUEeyt9O6Qe0AcVQ" type="3003" element="_CS49gOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_CS5kkuPUEeyt9O6Qe0AcVQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_CS5kk-PUEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CS5kkePUEeyt9O6Qe0AcVQ" x="386" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TwFNJOPUEeyt9O6Qe0AcVQ" type="3008" element="_TwFNIOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_TwFNJuPUEeyt9O6Qe0AcVQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TwFNJ-PUEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TwFNJePUEeyt9O6Qe0AcVQ" x="297" y="103" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_uVbJgePTEeyt9O6Qe0AcVQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_uVbJguPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_uVbJg-PTEeyt9O6Qe0AcVQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_uVbJh-PTEeyt9O6Qe0AcVQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uVbJhOPTEeyt9O6Qe0AcVQ" x="145" y="179"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_uzeXcOPTEeyt9O6Qe0AcVQ" type="3007" element="_uzdwYOPTEeyt9O6Qe0AcVQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_uze-gOPTEeyt9O6Qe0AcVQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_uze-gePTEeyt9O6Qe0AcVQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_KtMQWuPUEeyt9O6Qe0AcVQ" type="3063" element="_KtLpQOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KtMQXOPUEeyt9O6Qe0AcVQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KtMQW-PUEeyt9O6Qe0AcVQ" x="270" y="23" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TJd5E-PUEeyt9O6Qe0AcVQ" type="3008" element="_TJdSAOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_TJd5FePUEeyt9O6Qe0AcVQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_TJd5FuPUEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TJd5FOPUEeyt9O6Qe0AcVQ" x="430" y="31" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_c__SQOPUEeyt9O6Qe0AcVQ" type="3003" element="_c_-rMOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_c__SQuPUEeyt9O6Qe0AcVQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_c__SQ-PUEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_c__SQePUEeyt9O6Qe0AcVQ" x="561" y="37"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gCuqgOPUEeyt9O6Qe0AcVQ" type="3003" element="_gCuDcOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_gCuqguPUEeyt9O6Qe0AcVQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_gCuqg-PUEeyt9O6Qe0AcVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gCuqgePUEeyt9O6Qe0AcVQ" x="561" y="132"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_uzeXcePTEeyt9O6Qe0AcVQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_uzeXcuPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_uzeXc-PTEeyt9O6Qe0AcVQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_uze-guPTEeyt9O6Qe0AcVQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uzeXdOPTEeyt9O6Qe0AcVQ" x="200" y="183"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_qzi-O-PTEeyt9O6Qe0AcVQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_qzi-POPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_qzi-PePTEeyt9O6Qe0AcVQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_qzi-QePTEeyt9O6Qe0AcVQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qzi-PuPTEeyt9O6Qe0AcVQ" width="840" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_sZFjMOPUEeyt9O6Qe0AcVQ" type="2007" element="_sZEVEOPUEeyt9O6Qe0AcVQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_sZFjNePUEeyt9O6Qe0AcVQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_sZFjNuPUEeyt9O6Qe0AcVQ" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_wB-Vc-PUEeyt9O6Qe0AcVQ" type="3012" element="_wB9uYOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_wB-8gOPUEeyt9O6Qe0AcVQ" type="5029">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_wB-8gePUEeyt9O6Qe0AcVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wB-VdOPUEeyt9O6Qe0AcVQ" x="74" y="133"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_05uHgOPUEeyt9O6Qe0AcVQ" type="3027" element="_05tgcOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_05uHguPUEeyt9O6Qe0AcVQ" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_05uHgePUEeyt9O6Qe0AcVQ" x="164" y="122" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_2NfcgOPUEeyt9O6Qe0AcVQ" type="3027" element="_2Ne1cOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_2NfcguPUEeyt9O6Qe0AcVQ" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2NfcgePUEeyt9O6Qe0AcVQ" x="316" y="122" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_7GWo4-PUEeyt9O6Qe0AcVQ" type="3051" element="_7GWB0OPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_7GXP8OPUEeyt9O6Qe0AcVQ" type="5075">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_7GXP8ePUEeyt9O6Qe0AcVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7GWo5OPUEeyt9O6Qe0AcVQ" x="498" y="130" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_JwydBOPVEeyt9O6Qe0AcVQ" type="3013" element="_JwydAOPVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_JwzEEOPVEeyt9O6Qe0AcVQ" type="5027">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_JwzEEePVEeyt9O6Qe0AcVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JwydBePVEeyt9O6Qe0AcVQ" x="628" y="81" width="30" height="30"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_LjBPo-PVEeyt9O6Qe0AcVQ" type="3003" element="_LjAokOPVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_LjBPpePVEeyt9O6Qe0AcVQ" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_LjBPpuPVEeyt9O6Qe0AcVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LjBPpOPVEeyt9O6Qe0AcVQ" x="754" y="81"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_TErDMOPVEeyt9O6Qe0AcVQ" type="3017" element="_TEp1EOPVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_TErDMuPVEeyt9O6Qe0AcVQ" type="5032">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_TErDM-PVEeyt9O6Qe0AcVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TErDMePVEeyt9O6Qe0AcVQ" x="505" y="216"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_sZFjMePUEeyt9O6Qe0AcVQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_sZFjMuPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_sZFjM-PUEeyt9O6Qe0AcVQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_sZFjN-PUEeyt9O6Qe0AcVQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sZFjNOPUEeyt9O6Qe0AcVQ" width="894" height="306"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_qX8VYOPVEeyt9O6Qe0AcVQ" type="2007" element="_qX7uUOPVEeyt9O6Qe0AcVQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_qX8VZePVEeyt9O6Qe0AcVQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_qX8VZuPVEeyt9O6Qe0AcVQ" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_yXyg0OPVEeyt9O6Qe0AcVQ" type="3016" element="_yXx5wOPVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_yXyg0uPVEeyt9O6Qe0AcVQ" type="5031">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_yXyg0-PVEeyt9O6Qe0AcVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yXyg0ePVEeyt9O6Qe0AcVQ" x="92" y="72"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_QHqDB-PWEeyt9O6Qe0AcVQ" type="3027" element="_QHpb8OPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_QHqDCePWEeyt9O6Qe0AcVQ" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QHqDCOPWEeyt9O6Qe0AcVQ" x="177" y="63" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_buLaO-PWEeyt9O6Qe0AcVQ" type="3063" element="_buLaMOPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_buMBQOPWEeyt9O6Qe0AcVQ" type="5093"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_buLaPOPWEeyt9O6Qe0AcVQ" x="355" y="58" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_jjjbAOPWEeyt9O6Qe0AcVQ" type="3008" element="_jjiz8OPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_jjjbAuPWEeyt9O6Qe0AcVQ" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_jjjbA-PWEeyt9O6Qe0AcVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jjjbAePWEeyt9O6Qe0AcVQ" x="564" y="71" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_oRi0JOPWEeyt9O6Qe0AcVQ" type="3063" element="_oRiNEOPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_oRi0JuPWEeyt9O6Qe0AcVQ" type="5093"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oRi0JePWEeyt9O6Qe0AcVQ" x="682" y="70" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_uXFPAOPWEeyt9O6Qe0AcVQ" type="3003" element="_uXEA4OPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont">
          <children xmi:type="notation:DecorationNode" xmi:id="_uXFPAuPWEeyt9O6Qe0AcVQ" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_uXFPA-PWEeyt9O6Qe0AcVQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uXFPAePWEeyt9O6Qe0AcVQ" x="852" y="78"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_zTv9UePWEeyt9O6Qe0AcVQ" type="3027" element="_zTvWQOPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_zTv9U-PWEeyt9O6Qe0AcVQ" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zTv9UuPWEeyt9O6Qe0AcVQ" x="374" y="171" width="120" height="60"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_qX8VYePVEeyt9O6Qe0AcVQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_qX8VYuPVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_qX8VY-PVEeyt9O6Qe0AcVQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_qX8VZ-PVEeyt9O6Qe0AcVQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qX8VZOPVEeyt9O6Qe0AcVQ" width="992" height="291"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_n3sGzePSEeyt9O6Qe0AcVQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_n3sGzuPSEeyt9O6Qe0AcVQ" type="4001" element="_n3sGmOPSEeyt9O6Qe0AcVQ" source="_n3sGv-PSEeyt9O6Qe0AcVQ" target="_7nyz8OPSEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_n3sGz-PSEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_n3sG0OPSEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_n3sG0ePSEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_n3sG0uPSEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8nAOMOPSEeyt9O6Qe0AcVQ" type="4001" element="_8m_nIOPSEeyt9O6Qe0AcVQ" source="_7nyz8OPSEeyt9O6Qe0AcVQ" target="_-1zBAOPSEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8nAOM-PSEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8nAONOPSEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8nAOMePSEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8nAOMuPSEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DEZvcOPTEeyt9O6Qe0AcVQ" type="4001" element="_DEZIYOPTEeyt9O6Qe0AcVQ" source="_AGvrgOPTEeyt9O6Qe0AcVQ" target="_7nyz8OPSEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DEZvc-PTEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DEZvdOPTEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DEZvcePTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DEZvcuPTEeyt9O6Qe0AcVQ" points="[-13, 0, 150, 27]$[-13, 22, 150, 49]$[-155, 22, 8, 49]$[-155, -13, 8, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DEaWgOPTEeyt9O6Qe0AcVQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DEaWgePTEeyt9O6Qe0AcVQ" id="(0.43333333333333335,0.7666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KB6UIOPTEeyt9O6Qe0AcVQ" type="4001" element="_KB5tEOPTEeyt9O6Qe0AcVQ" source="_-1zBAOPSEeyt9O6Qe0AcVQ" target="_KhS-0-PTEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KB6UI-PTEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KB6UJOPTEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KB6UIePTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KB6UIuPTEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_L8JMMOPTEeyt9O6Qe0AcVQ" type="4001" element="_L8IlIOPTEeyt9O6Qe0AcVQ" source="_KhS-0-PTEeyt9O6Qe0AcVQ" target="_L8E6xOPTEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_L8JMM-PTEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_L8JMNOPTEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_L8JMMePTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_L8JMMuPTEeyt9O6Qe0AcVQ" points="[0, 22, -148, -35]$[0, 56, -148, -1]$[133, 56, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MyDggOPTEeyt9O6Qe0AcVQ" type="4001" element="_MyBEQOPTEeyt9O6Qe0AcVQ" source="_KhS-0-PTEeyt9O6Qe0AcVQ" target="_Mx8y0-PTEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MyDgg-PTEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MyDghOPTEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MyDggePTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MyDgguPTEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_53k-E-PTEeyt9O6Qe0AcVQ" type="4001" element="_53k-EOPTEeyt9O6Qe0AcVQ" source="_zcns0OPTEeyt9O6Qe0AcVQ" target="_6aIRiuPTEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_53k-FuPTEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_53k-F-PTEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_53k-FOPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_53k-FePTEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-2S60-PTEeyt9O6Qe0AcVQ" type="4001" element="_-2S60OPTEeyt9O6Qe0AcVQ" source="_6aIRiuPTEeyt9O6Qe0AcVQ" target="_TwFNJOPUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-2S61uPTEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-2S61-PTEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-2S61OPTEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-2S61ePTEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CS8A0-PUEeyt9O6Qe0AcVQ" type="4001" element="_CS8A0OPUEeyt9O6Qe0AcVQ" source="_TwFNJOPUEeyt9O6Qe0AcVQ" target="_CS5kkOPUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CS8A1uPUEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CS8A1-PUEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CS8A1OPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CS8A1ePUEeyt9O6Qe0AcVQ" points="[22, 0, -61, -1]$[68, 0, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KKcvouPUEeyt9O6Qe0AcVQ" type="4001" element="_KKcIkOPUEeyt9O6Qe0AcVQ" source="_TwFNJOPUEeyt9O6Qe0AcVQ" target="_KtMQWuPUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KKcvpePUEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KKcvpuPUEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KKcvo-PUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KKcvpOPUEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QyFK8-PUEeyt9O6Qe0AcVQ" type="4001" element="_QyFK8OPUEeyt9O6Qe0AcVQ" source="_KtMQWuPUEeyt9O6Qe0AcVQ" target="_TJd5E-PUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QyFK9uPUEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QyFK9-PUEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QyFK9OPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QyFK9ePUEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dAC8o-PUEeyt9O6Qe0AcVQ" type="4001" element="_dAC8oOPUEeyt9O6Qe0AcVQ" source="_TJd5E-PUEeyt9O6Qe0AcVQ" target="_c__SQOPUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dAC8puPUEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dAC8p-PUEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dAC8pOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dAC8pePUEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gCzjAOPUEeyt9O6Qe0AcVQ" type="4001" element="_gCxt0OPUEeyt9O6Qe0AcVQ" source="_TJd5E-PUEeyt9O6Qe0AcVQ" target="_gCuqgOPUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gCzjA-PUEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gCzjBOPUEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gCzjAePUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gCzjAuPUEeyt9O6Qe0AcVQ" points="[0, 22, -125, -73]$[0, 94, -125, -1]$[110, 94, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_05xK0OPUEeyt9O6Qe0AcVQ" type="4001" element="_05wjwOPUEeyt9O6Qe0AcVQ" source="_wB-Vc-PUEeyt9O6Qe0AcVQ" target="_05uHgOPUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_05xK0-PUEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_05xK1OPUEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_05xK0ePUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_05xK0uPUEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2Nh4w-PUEeyt9O6Qe0AcVQ" type="4001" element="_2Nh4wOPUEeyt9O6Qe0AcVQ" source="_05uHgOPUEeyt9O6Qe0AcVQ" target="_2NfcgOPUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2Nif0OPUEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2Nif0ePUEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2Nh4xOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2Nh4xePUEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6uC2k-PUEeyt9O6Qe0AcVQ" type="4001" element="_6uC2kOPUEeyt9O6Qe0AcVQ" source="_2NfcgOPUEeyt9O6Qe0AcVQ" target="_7GWo4-PUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6uC2luPUEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6uC2l-PUEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6uC2lOPUEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6uC2lePUEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EF7zAOPVEeyt9O6Qe0AcVQ" type="4001" element="_EF7L8OPVEeyt9O6Qe0AcVQ" source="_7GWo4-PUEeyt9O6Qe0AcVQ" target="_JwydBOPVEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EF7zA-PVEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EF7zBOPVEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EF7zAePVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EF7zAuPVEeyt9O6Qe0AcVQ" points="[-22, -29, -116, 39]$[-22, -65, -116, 3]$[87, -65, -7, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EF8aEOPVEeyt9O6Qe0AcVQ" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EF8aEePVEeyt9O6Qe0AcVQ" id="(0.23333333333333334,0.3333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LjGIIOPVEeyt9O6Qe0AcVQ" type="4001" element="_LjFhEOPVEeyt9O6Qe0AcVQ" source="_JwydBOPVEeyt9O6Qe0AcVQ" target="_LjBPo-PVEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LjGII-PVEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LjGIJOPVEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LjGIIePVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LjGIIuPVEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UGyAcuPVEeyt9O6Qe0AcVQ" type="4001" element="_UGxZYOPVEeyt9O6Qe0AcVQ" source="_7GWo4-PUEeyt9O6Qe0AcVQ" target="_TErDMOPVEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UGyAdePVEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UGyAduPVEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UGyAc-PVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UGyAdOPVEeyt9O6Qe0AcVQ" points="[-21, 14, 0, -60]$[-6, 74, 15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UGzOkOPVEeyt9O6Qe0AcVQ" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UyMU8ePVEeyt9O6Qe0AcVQ" type="4001" element="_UyLt4OPVEeyt9O6Qe0AcVQ" source="_TErDMOPVEeyt9O6Qe0AcVQ" target="_05uHgOPUEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UyMU9OPVEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UyMU9ePVEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UyMU8uPVEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UyMU8-PVEeyt9O6Qe0AcVQ" points="[-30, -16, 265, 56]$[-312, -16, -17, 56]$[-312, -64, -17, 8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UyNjEOPVEeyt9O6Qe0AcVQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UyNjEePVEeyt9O6Qe0AcVQ" id="(0.6333333333333333,0.8666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QHtGUOPWEeyt9O6Qe0AcVQ" type="4001" element="_QHsfQOPWEeyt9O6Qe0AcVQ" source="_yXyg0OPVEeyt9O6Qe0AcVQ" target="_QHqDB-PWEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QHtGU-PWEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QHtGVOPWEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QHtGUePWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QHtGUuPWEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Twmfo-PWEeyt9O6Qe0AcVQ" type="4001" element="_TwmfoOPWEeyt9O6Qe0AcVQ" source="_QHqDB-PWEeyt9O6Qe0AcVQ" target="_buLaO-PWEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TwmfpuPWEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Twmfp-PWEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TwmfpOPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TwmfpePWEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jDpy8-PWEeyt9O6Qe0AcVQ" type="4001" element="_jDpy8OPWEeyt9O6Qe0AcVQ" source="_buLaO-PWEeyt9O6Qe0AcVQ" target="_jjjbAOPWEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jDpy9uPWEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jDpy9-PWEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jDpy9OPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jDpy9ePWEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kX63M-PWEeyt9O6Qe0AcVQ" type="4001" element="_kX63MOPWEeyt9O6Qe0AcVQ" source="_jjjbAOPWEeyt9O6Qe0AcVQ" target="_oRi0JOPWEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kX63NuPWEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kX63N-PWEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kX63NOPWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kX63NePWEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uXHrQuPWEeyt9O6Qe0AcVQ" type="4001" element="_uXHEMOPWEeyt9O6Qe0AcVQ" source="_oRi0JOPWEeyt9O6Qe0AcVQ" target="_uXFPAOPWEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uXHrRePWEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uXHrRuPWEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uXHrQ-PWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uXHrROPWEeyt9O6Qe0AcVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zT1c4OPWEeyt9O6Qe0AcVQ" type="4001" element="_zTyZkOPWEeyt9O6Qe0AcVQ" source="_jjjbAOPWEeyt9O6Qe0AcVQ" target="_zTv9UePWEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zT1c4-PWEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zT1c5OPWEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zT1c4ePWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zT1c4uPWEeyt9O6Qe0AcVQ" points="[0, 22, 151, -87]$[0, 109, 151, 0]$[-91, 109, 60, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1T7sYOPWEeyt9O6Qe0AcVQ" type="4001" element="_1T7FUOPWEeyt9O6Qe0AcVQ" source="_zTv9UePWEeyt9O6Qe0AcVQ" target="_QHqDB-PWEeyt9O6Qe0AcVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1T7sY-PWEeyt9O6Qe0AcVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1T7sZOPWEeyt9O6Qe0AcVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1T7sYePWEeyt9O6Qe0AcVQ" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1T7sYuPWEeyt9O6Qe0AcVQ" points="[-120, -3, 149, 91]$[-229, -3, 40, 91]$[-229, -80, 40, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1T8TcOPWEeyt9O6Qe0AcVQ" id="(1.0,0.5333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1T8TcePWEeyt9O6Qe0AcVQ" id="(0.4,0.7666666666666667)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
